import requests
import json
from typing import Type, Any
from pydantic import BaseModel
from google import genai
from google.genai import types
import core.config as config
from core.schemas import MlirResponse

def run_kimi(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to the NVIDIA API (Kimi proxy).
    
    Args:
        system_p (str): System prompt (context/rules).
        user_p (str): User prompt (specific instruction).
        schema (Type[BaseModel], optional): Pydantic model for Constrained Decoding.

    Returns:
        str: Raw response generated by the model.
    """
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {config.NVIDIA_API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": config.MODEL_KIMI,
        "messages": [
            {"role": "system", "content": system_p},
            {"role": "user", "content": user_p}
        ],
        "max_tokens": config.GENERATION_PARAMS["max_tokens"],
        "temperature": config.GENERATION_PARAMS["temperature"],
        "top_p": config.GENERATION_PARAMS["top_p"],
        "stream": False
    }
    
    # Kimi/OpenAI fallback for Constrained Decoding
    if schema:
        payload["response_format"] = {"type": "json_object"}
        
    response = requests.post(url, headers=headers, json=payload)
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]

def run_gemini(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to Gemini with Constrained Decoding support.
    
    Args:
        system_p (str): System prompt (context/rules).
        user_p (str): User prompt (specific instruction).
        schema (Type[BaseModel], optional): Pydantic model for Constrained Decoding.

    Returns:
        str: Raw response generated by the model.
    """
    client = genai.Client(api_key=config.GEMINI_API_KEY)
    
    # Base configuration
    config_params = {
        "system_instruction": system_p,
        "temperature": config.GENERATION_PARAMS["temperature"],
        "max_output_tokens": config.GENERATION_PARAMS["max_tokens"]
    }
    
    # Enable Gemini's native XGrammar/Structured Outputs
    if schema:
        config_params["response_mime_type"] = "application/json"
        config_params["response_schema"] = schema
        
    gl_config = types.GenerateContentConfig(**config_params)
    
    response = client.models.generate_content(
        model=config.MODEL_GEMINI,
        contents=user_p,
        config=gl_config
    )
    return response.text

def run_ollama(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to a local Ollama server with Constrained Decoding support.
    
    Args:
        system_p (str): System prompt (context/rules).
        user_p (str): User prompt (specific instruction).
        schema (Type[BaseModel], optional): Pydantic model for Constrained Decoding.

    Returns:
        str: Raw response generated by the model.
    """
    payload = {
        "model": config.MODEL_OLLAMA,
        "messages": [
            {"role": "system", "content": system_p},
            {"role": "user", "content": user_p}
        ],
        "options": {
            "temperature": config.GENERATION_PARAMS["temperature"],
            "top_p": config.GENERATION_PARAMS["top_p"],
            "num_predict": config.GENERATION_PARAMS["max_tokens"]
        },
        "stream": False
    }

    # Enable Ollama native Structured Outputs
    if schema:
        payload["format"] = schema.model_json_schema()

    response = requests.post(config.OLLAMA_ENDPOINT, json=payload)
    response.raise_for_status()
    
    return response.json()["message"]["content"]

def run_remote(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to the remote Kaggle endpoint.
    """
    # The remote API expects 'prompt' and 'max_tokens'
    prompt = f"<bos><start_of_turn>user\n{system_p}\n\n{user_p}<end_of_turn>\n<start_of_turn>model\n"
    
    payload = {
        "prompt": prompt,
        "max_tokens": config.GENERATION_PARAMS["max_tokens"]
    }
    
    if schema:
        # Enviar el schema JSON para que Kaggle aplique XGrammar
        payload["schema"] = schema.model_json_schema()
        
    url = f"{config.REMOTE_MODEL_URL.rstrip('/')}/generate"
    response = requests.post(url, json=payload, timeout=600)
    response.raise_for_status()
    
    res_text = response.json().get("response", "")
    
    # Strip the prompt if it's echoed back
    if res_text.startswith(prompt):
        res_text = res_text[len(prompt):].strip()
        
    return res_text

def generate_llm_response(model_name: str, system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Agnostic router with support for structured decoding.
    
    Allows swapping the underlying LLM without altering the pipeline.
    
    Args:
        model_name (str): 'kimi', 'gemini' or 'ollama'.
        system_p (str): System prompt.
        user_p (str): User prompt.
        schema (Type[BaseModel], optional): Pydantic model to enforce output structure.

    Returns:
        str: Response from the selected LLM.

    Raises:
        ValueError: If the requested model is not supported.
    """
    if getattr(config, "USE_REMOTE_MODEL", False):
        return run_remote(system_p, user_p, schema)

    name = model_name.lower()
    if name == "kimi":
        return run_kimi(system_p, user_p, schema)
    elif name == "gemini":
        return run_gemini(system_p, user_p, schema)
    elif name == "ollama":
        return run_ollama(system_p, user_p, schema)
    else:
        raise ValueError(f"Frontier model not supported: {model_name}")
