import requests
import json
from typing import Type, Any
from pydantic import BaseModel
from google import genai
from google.genai import types
import core.config as config
from core.schemas import MlirResponse
import time

def run_kimi(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to the NVIDIA API (Kimi proxy).
    
    Args:
        system_p (str): System prompt (context/rules).
        user_p (str): User prompt (specific instruction).
        schema (Type[BaseModel], optional): Pydantic model for Constrained Decoding.

    Returns:
        str: Raw response generated by the model.
    """
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {config.NVIDIA_API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": config.MODEL_KIMI,
        "messages": [
            {"role": "system", "content": system_p},
            {"role": "user", "content": user_p}
        ],
        "max_tokens": config.GENERATION_PARAMS["max_tokens"],
        "temperature": config.GENERATION_PARAMS["temperature"],
        "top_p": config.GENERATION_PARAMS["top_p"],
        "stream": False
    }
    
    # Kimi/OpenAI fallback for Constrained Decoding
    if schema:
        payload["response_format"] = {
        "type": "json_schema",
        "json_schema": {
            "name": "mlir_response",
            "schema": schema.model_json_schema(),
            "strict": True 
        }
    }
        
    response = requests.post(url, headers=headers, json=payload)
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]

def run_gemini(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to Gemini with Constrained Decoding support.
    
    Args:
        system_p (str): System prompt (context/rules).
        user_p (str): User prompt (specific instruction).
        schema (Type[BaseModel], optional): Pydantic model for Constrained Decoding.

    Returns:
        str: Raw response generated by the model.
    """
    # Initialize Vertex AI client using Application Default Credentials
    client = genai.Client(vertexai=True, project=config.GCP_PROJECT_ID, location=config.GCP_LOCATION)
    
    # Base configuration
    config_params = {
        "system_instruction": system_p,
        "temperature": config.GENERATION_PARAMS["temperature"],
        "max_output_tokens": config.GENERATION_PARAMS["max_tokens"]
    }
    
    # Enable Gemini's native XGrammar/Structured Outputs
    if schema:
        config_params["response_mime_type"] = "application/json"
        config_params["response_schema"] = schema
        
    gl_config = types.GenerateContentConfig(**config_params)
    
    response = client.models.generate_content(
        model=config.MODEL_GEMINI,
        contents=user_p,
        config=gl_config
    )
    return response.text

def run_ollama(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to a local Ollama server with Constrained Decoding support.
    
    Args:
        system_p (str): System prompt (context/rules).
        user_p (str): User prompt (specific instruction).
        schema (Type[BaseModel], optional): Pydantic model for Constrained Decoding.

    Returns:
        str: Raw response generated by the model.
    """
    payload = {
        "model": config.MODEL_OLLAMA,
        "messages": [
            {"role": "system", "content": system_p},
            {"role": "user", "content": user_p}
        ],
        "options": {
            "temperature": config.GENERATION_PARAMS["temperature"],
            "top_p": config.GENERATION_PARAMS["top_p"],
            "num_predict": config.GENERATION_PARAMS["max_tokens"]
        },
        "stream": False
    }

    # Enable Ollama native Structured Outputs
    if schema:
        payload["format"] = schema.model_json_schema()

    response = requests.post(config.OLLAMA_ENDPOINT, json=payload)
    response.raise_for_status()
    
    return response.json()["message"]["content"]

def run_remote(system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Makes a request to the remote Kaggle endpoint.
    """
    # The remote API expects 'prompt' and 'max_tokens'
    prompt = (
        f"<|im_start|>system\n{system_p}<|im_end|>\n"
        f"<|im_start|>user\n{user_p}<|im_end|>\n"
        f"<|im_start|>assistant\n"
    )
    payload = {"prompt": prompt, "max_tokens": config.GENERATION_PARAMS["max_tokens"]}
    if schema:
        payload["schema_dict"] = schema.model_json_schema()

    url = config.REMOTE_MODEL_URL.rstrip('/')
    
    # 1. Dispatch the job (returns immediately)
    response = requests.post(f"{url}/generate", json=payload, timeout=30)
    response.raise_for_status()
    job_id = response.json()["job_id"]
    print(f"[Remote] Job dispatched: {job_id}. Waiting for result...")

    # 2. Poll until completion
    poll_interval = 8  # seconds between checks
    max_wait = 600     # 10 minutes maximum
    elapsed = 0

    while elapsed < max_wait:
        time.sleep(poll_interval)
        elapsed += poll_interval
        
        status_resp = requests.get(f"{url}/status/{job_id}", timeout=15)
        status_resp.raise_for_status()
        data = status_resp.json()

        if data["status"] == "done":
            res_text = data["response"]
            # Strip prompt wrapper if present in the response
            if res_text.startswith(prompt):
                res_text = res_text[len(prompt):].strip()
            return res_text
        elif data["status"] == "error":
            raise RuntimeError(f"Remote server error: {data['error']}")
        else:
            print(f"[Remote] Pending... ({elapsed}s)")

    raise TimeoutError(f"Job {job_id} did not complete within {max_wait}s")

def generate_llm_response(model_name: str, system_p: str, user_p: str, schema: Type[BaseModel] = None) -> str:
    """
    Agnostic router with support for structured decoding.
    
    Allows swapping the underlying LLM without altering the pipeline.
    
    Args:
        model_name (str): 'kimi', 'gemini' or 'ollama'.
        system_p (str): System prompt.
        user_p (str): User prompt.
        schema (Type[BaseModel], optional): Pydantic model to enforce output structure.

    Returns:
        str: Response from the selected LLM.

    Raises:
        ValueError: If the requested model is not supported.
    """
    if getattr(config, "USE_REMOTE_MODEL", False):
        return run_remote(system_p, user_p, schema)

    name = model_name.lower()
    if name == "kimi":
        return run_kimi(system_p, user_p, schema)
    elif name == "gemini":
        return run_gemini(system_p, user_p, schema)
    elif name == "ollama":
        return run_ollama(system_p, user_p, schema)
    else:
        raise ValueError(f"Frontier model not supported: {model_name}")
