import json

class PromptBuilder:
    """
    Constructs the system prompt for the LLM dynamically based on the user's query.
    Implements a simple RAG (Retrieval-Augmented Generation) heuristic.
    """
    
    def __init__(self):
        self.base_rules = (
            "CRITICAL RULES:\n"
            "1. Immutability & Scoping: Each operation saves its result in a new temporary register (e.g., '%0'). "
            "Registers defined inside a block (e.g., scf.for) CANNOT be accessed outside.\n"
            "2. TOPOLOGICAL ORDERING: You MUST define a register BEFORE you use it. For example, create '%mask' using 'arith.cmpf' BEFORE using it in 'tt.load'.\n"
            "3. NO UNDECLARED VARIABLES: You CANNOT use any register as an operand unless EXPLICITLY defined beforehand. No forward references.\n"
            "4. TYPE MATCHING: 'arith.addf', 'arith.divf', 'arith.mulf' require EXACTLY the same shape and type. You CANNOT directly add a tensor and a scalar ('f32'). First broadcast the scalar using 'tt.splat', then apply math. DO NOT use pointers ('!tt.ptr<f32>') in math operations.\n"
            "5. FLOAT OPERATIONS: 'arith.divf', 'arith.addf', 'math.exp' expect float types ('f32', 'tensor<...xf32>'). DO NOT pass integers ('i32', 'index') to float math ops.\n"
            "6. POINTERS: 'tt.load' and 'tt.store' operate on pointers. 'tt.load' returns math values (tensors/f32), NOT pointers. 'tt.store' consumes math values and writes to pointers.\n"
            "7. TT.STORE OPERAND ORDER: For 'tt.store', the FIRST operand MUST be the pointer ('%ptr'), and the SECOND operand MUST be the value ('%val'). e.g., operands: ['%ptr', '%val']. DO NOT swap them!\n"
            "8. SPMD PARADIGM: Do NOT use 'scf.for' to iterate over the grid or PIDs! The Triton kernel runs per-block. Use 'tt.get_program_id' (with 'axis' attribute) to get the block index. ONLY use 'scf.for' for loops WITHIN a block (e.g., reduction over sequence length).\n"
            "9. SCF.FOR CORRECTNESS: If you use 'scf.for', it MUST have an 'scf.yield' as its LAST operation. The number of 'results' must EXACTLY match the number of 'iter_args', and 'scf.yield' must return exactly that many operands.\n"
            "10. REDUCE COMBINERS: 'tt.reduce' region_combiner MUST be a binary op (e.g. 'arith.addf', 'arith.maximumf'). NEVER use unary ops like 'math.exp'.\n"
            "11. CMP ATTRIBUTES: 'arith.cmpf' (for floats) and 'arith.cmpi' (for ints/index) REQUIRE a 'predicate' attribute inside the 'attributes' dict (e.g., {\"attributes\": {\"predicate\": 1}} for OGT or {\"attributes\": {\"predicate\": 2}} for SLT). Do NOT put it at the root of the JSON.\n"
            "12. CONSTANTS: You CANNOT pass numeric literals (like 1024 or 0.0) directly as operands to most instructions. You MUST create them first using 'arith.constant' (e.g., {\"opcode\": \"arith.constant\", \"attributes\": {\"value\": 1024}, \"result\": \"%c1024\", \"out_type\": \"i32\"}) and pass the register.\n"
            "13. OUT_TYPE IS MANDATORY FOR MEMORY: Operations like 'tt.make_range', 'tt.splat', 'tt.addptr', and 'tt.load' MUST have an explicit 'out_type'. If you omit it, the compiler will assume they return pointers and math operations like 'arith.addf' will fail!\n"
            "14. MAKE_RANGE ARITY: 'tt.make_range' takes EXACTLY 0 operands. Pass an empty list: \"operands\": []. It REQUIRES 'start' and 'end' in 'attributes'. Its out_type MUST be a tensor of integers (e.g., 'tensor<256xi32>').\n"
            "15. KERNEL RETURNS: The main 'code' block must ALWAYS return an empty list: \"returns\": []. Triton GPU kernels modify global memory via 'tt.store', they do not return variables.\n"
            "16. HARDWARE BLOCK SIZES: GPUs operate on strict powers of 2. For any tensor shape, you MUST pick a power of 2 from the allowed schema (e.g., 16, 32, 64, 128, 256, 512, 1024). NEVER use arbitrary sizes like 100 or 150. If the problem specifies arbitrary bounds, pad it using a boolean mask ('tensor<...xi1>') generated by 'arith.cmpi'.\n"
        )
        
        self.few_shot_examples = (
            "GENERIC MLIR PARADIGMS (Use these as reference for your JSON structure):\n"
            "- SPMD KERNEL PARADIGM (No loops for grid): Use `tt.get_program_id` with `\"attributes\": {\"axis\": 0}` (and NO operands) to get the block ID, then multiply by BLOCK_SIZE to get the base offset for this block.\n"
            "- MEMORY BLOCK PARADIGM: To read global memory, strictly follow this sequence:\n"
            "  1. tt.make_range -> %offsets\n"
            "  2. tt.splat(%base_ptr) -> %splat_ptr\n"
            "  3. tt.addptr(%splat_ptr, %offsets) -> %block_ptrs\n"
            "  4. arith.constant(N) -> %c_limit\n"
            "  5. tt.splat(%c_limit) -> %splat_limit\n"
            "  6. arith.cmpi (with attributes: {\"predicate\": 2}) on [%offsets, %splat_limit] -> %mask\n"
            "  7. tt.load(%block_ptrs, %mask) -> %values\n\n"
            "- SCF.FOR LOOP PARADIGM (ONLY for loops WITHIN a block, like reducing along K dimension):\n"
            "  {\"opcode\":\"scf.for\", \"lower_bound\":0, \"upper_bound\":128, \"step\":1, \"loop_var\":\"%i\", \"iter_args\":{\"%sum\":0.0}, \"results\":[\"%out\"], \"body\": [\n"
            "    {\"opcode\":\"tt.load\", \"operands\":[\"%ptr\"], \"result\":\"%v\"},\n"
            "    {\"opcode\":\"arith.addf\", \"operands\":[\"%sum\",\"%v\"], \"result\":\"%n\"},\n"
            "    {\"opcode\":\"scf.yield\", \"operands\":[\"%n\"]}\n"
            "  ]}\n\n"
            "- TT.REDUCE PARADIGM:\n"
            "  {\"opcode\": \"tt.reduce\", \"operands\": [\"%tensor\"], \"result\": \"%row_sum\", \"region_combiner\": \"arith.addf\", \"attributes\": {\"axis\": 0}}\n"
            "  NOTE: `region_combiner` MUST be a valid binary op like `arith.addf`, `arith.maximumf`. NEVER use unary ops like `math.exp`.\n\n"
            "- PERFECT VECTOR ADD JSON (Use this exact structure for simple kernels):\n"
            "{\n"
            "  \"code\": {\n"
            "    \"function_name\": \"vec_sum_kernel\",\n"
            "    \"arguments\": [\n"
            "      {\"name\": \"%arg0_A\", \"type\": \"!tt.ptr<f32>\"},\n"
            "      {\"name\": \"%arg1_B\", \"type\": \"!tt.ptr<f32>\"},\n"
            "      {\"name\": \"%arg2_C\", \"type\": \"!tt.ptr<f32>\"}\n"
            "    ],\n"
            "    \"operations\": [\n"
            "      {\"opcode\": \"tt.make_range\", \"operands\": [], \"attributes\": {\"start\": 0, \"end\": 256}, \"result\": \"%offsets\", \"out_type\": \"tensor<256xi32>\"},\n"
            "      {\"opcode\": \"tt.splat\", \"operands\": [\"%arg0_A\"], \"result\": \"%ptrs_A\", \"out_type\": \"tensor<256x!tt.ptr<f32>>\"},\n"
            "      {\"opcode\": \"tt.addptr\", \"operands\": [\"%ptrs_A\", \"%offsets\"], \"result\": \"%ptrs_A_off\", \"out_type\": \"tensor<256x!tt.ptr<f32>>\"},\n"
            "      {\"opcode\": \"tt.load\", \"operands\": [\"%ptrs_A_off\"], \"result\": \"%val_A\", \"out_type\": \"tensor<256xf32>\"},\n"
            "      {\"opcode\": \"tt.splat\", \"operands\": [\"%arg1_B\"], \"result\": \"%ptrs_B\", \"out_type\": \"tensor<256x!tt.ptr<f32>>\"},\n"
            "      {\"opcode\": \"tt.addptr\", \"operands\": [\"%ptrs_B\", \"%offsets\"], \"result\": \"%ptrs_B_off\", \"out_type\": \"tensor<256x!tt.ptr<f32>>\"},\n"
            "      {\"opcode\": \"tt.load\", \"operands\": [\"%ptrs_B_off\"], \"result\": \"%val_B\", \"out_type\": \"tensor<256xf32>\"},\n"
            "      {\"opcode\": \"arith.addf\", \"operands\": [\"%val_A\", \"%val_B\"], \"result\": \"%val_C\", \"out_type\": \"tensor<256xf32>\"},\n"
            "      {\"opcode\": \"tt.splat\", \"operands\": [\"%arg2_C\"], \"result\": \"%ptrs_C\", \"out_type\": \"tensor<256x!tt.ptr<f32>>\"},\n"
            "      {\"opcode\": \"tt.addptr\", \"operands\": [\"%ptrs_C\", \"%offsets\"], \"result\": \"%ptrs_C_off\", \"out_type\": \"tensor<256x!tt.ptr<f32>>\"},\n"
            "      {\"opcode\": \"tt.store\", \"operands\": [\"%ptrs_C_off\", \"%val_C\"], \"result\": \"none\"}\n"
            "    ],\n"
            "    \"returns\": []\n"
            "  }\n"
            "}\n"
        )
        
        self.scf_rules = ""
        self.reduce_rules = ""
        self.block_rules = ""
        
        import os
        self.mlir_ops_csv_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "mlir_operations.csv")
        
        self.triton_ops_registry = {
            "arith.cmpi": "Compares integers. Requires 'predicate' attribute inside 'attributes' dict. Operands: [lhs, rhs].",
            "arith.cmpf": "Compares floats. Requires 'predicate' attribute inside 'attributes' dict. Operands: [lhs, rhs].",
            "tt.get_program_id": "Returns the id of the current program. Requires 'axis' attribute (int). Takes EXACTLY 0 operands (pass []). Example attributes: {\"axis\": 0}",
            "tt.make_range": "Returns a tensor of indices. Requires 'start' and 'end' attributes (int). Takes EXACTLY 0 operands (pass []). Example attributes: {\"start\": 0, \"end\": 1024}",
            "tt.splat": "Broadcasts a scalar to a tensor of a given shape. Requires 'shape' attribute (list of ints). Operands: [value].",
            "tt.expand_dims": "Inserts a size-1 dimension into a tensor's shape. Requires 'dimension_to_expand' attribute (int). Operands: [tensor].",
            "tt.addptr": "Adds an offset to a tensor of pointers. Operands: [base_ptr, offset].",
            "tt.load": "Loads data from a pointer or tensor of pointers. Operands: [ptr_tensor].",
            "tt.store": "Stores data to a pointer or tensor of pointers. Operands: [ptr_tensor, value_tensor].",
            "tt.dot": "Performs matrix multiplication. Operands: [tensor_a, tensor_b]."
        }

    def _fetch_rag_context(self, user_prompt: str) -> str:
        prompt_words = set(user_prompt.lower().replace(",", " ").replace(".", " ").split())
        context_lines = []
        
        # 1. Search Triton dictionary
        for op, desc in self.triton_ops_registry.items():
            op_keywords = set(op.replace("tt.", "").split("_"))
            if op_keywords.intersection(prompt_words):
                context_lines.append(f"- {op}: {desc}")
                
        # 2. Search MLIR CSV
        import csv
        import os
        if os.path.exists(self.mlir_ops_csv_path):
            with open(self.mlir_ops_csv_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    op_json = row.get("Operacion_JSON_op", "")
                    desc = row.get("Descripcion", "")
                    if not op_json or not desc or desc.strip() == "Sin descripción":
                        continue
                    
                    # Extract keywords from opcode
                    op_keywords = set(op_json.split(".")[-1].split("_"))
                    if op_keywords.intersection(prompt_words):
                        context_lines.append(f"- {op_json}: {desc}")
                        
        if context_lines:
            return "DYNAMIC RAG CONTEXT FOR OPERATIONS:\n" + "\n".join(context_lines) + "\n"
        return ""

    def build_prompt(self, user_prompt: str, json_schema: dict) -> str:
        """
        Builds the system prompt by dynamically injecting rules based on keywords.
        """
        schema_str = json.dumps(json_schema)
        
        prompt = (
            "Role: You are a Block-Level GPU Architect and expert LLM compiler in Triton MLIR. "
            "Your job is to translate high-level mathematical descriptions to a strict intermediate language in JSON format (Static Single Assignment - SSA).\n\n"
            f"You must output ONLY a valid JSON object that EXACTLY complies with the following JSON Schema:\n{schema_str}\n\n"
        )
        
        prompt += self.base_rules + "\n"
        
        user_prompt_lower = user_prompt.lower()
        
        if "online" in user_prompt_lower or "dynamic" in user_prompt_lower:
            prompt += (
                "ONLINE ALGORITHM RULES:\n"
                "- When an 'online' algorithm is requested (like online softmax), use an 'scf.for' loop to iterate and maintain running state via 'iter_args'.\n"
            )

        prompt += self.few_shot_examples + "\n"
            
        if any(word in user_prompt_lower for word in ["mask", "dynamic", "any size", "size"]):
            prompt += (
                "MEMORY MASKING RULE:\n"
                "- If the tensor size is dynamic, compute a boolean mask using arith.cmpi (comparing %offsets against tensor size).\n"
                "- Pass this mask to tt.load: tt.load(%ptrs, %mask).\n"
            )
            
        prompt += self._fetch_rag_context(user_prompt) + "\n"
            
        prompt += (
            "Output Format: DO NOT include markdown code blocks (e.g., ```json) or text outside the JSON. "
            "Your output must be parseable by json.loads().\n"
        )
        
        return prompt
